name: ESP32-S3 PlatformIO Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ✅ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # ✅ Install PlatformIO & esptool
      - name: Install PlatformIO & esptool
        run: |
          python -m pip install --upgrade pip
          pip install platformio esptool

      # ✅ Build firmware with PlatformIO
      - name: Build firmware
        run: pio run

      # ✅ Merge bootloader + partitions + firmware
      - name: Merge full firmware
        run: |
          esptool --chip esp32s3 merge-bin -o full_firmware.bin \
            --flash-mode dio --flash-freq 80m --flash-size 16MB \
            0x0 .pio/build/esp32-s3-devkitc-1/bootloader.bin \
            0x8000 .pio/build/esp32-s3-devkitc-1/partitions.bin \
            0x10000 .pio/build/esp32-s3-devkitc-1/firmware.bin

      # ✅ Upload merged firmware as artifact
      - name: Upload merged firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: full_firmware.bin
