name: ESP32 Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install PlatformIO
        run: pip install platformio
      - name: Build firmware
        run: pio run
      - name: Upload firmware as artifact
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: .pio/build/esp32-s3-devkitc-1/firmware.bin
