name: ESP32-S3 Waveshare Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PlatformIO
        run: |
          python3 -m pip install --upgrade pip
          pip install platformio

      - name: Build firmware
        run: pio run --environment esp32-s3-lcd-147

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: .pio/build/esp32-s3-lcd-147/firmware.bin
