name: Build ESP32S3 Hello World

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install ESP32 core
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: Install TFT_eSPI
        run: |
          arduino-cli lib install "TFT_eSPI"

      - name: Compile sketch
        run: |
          arduino-cli compile \
            --fqbn esp32:esp32:esp32s3:USBMode=default,PartitionScheme=huge_app,FlashSize=8M \
            display_test

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: esp32s3_hello_world_firmware
          path: |
            display_test/build/esp32.esp32.esp32s3/display_test.ino.bin
