name: ESP32-S3 Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: |
          pip install platformio
      - run: pio run
      - run: esptool.py merge_bin \
          -o full_firmware.bin \
          --flash_mode dio --flash_freq 80m --flash_size 16MB \
          0x0 .pio/build/*/bootloader.bin \
          0x8000 .pio/build/*/partition*.bin \
          0x10000 .pio/build/*/firmware.bin
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: full_firmware.bin
