name: Build ESP32-S3 Hello World

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install ESP-IDF
      run: |
        sudo apt-get update
        sudo apt-get install -y git wget flex bison gperf python3 python3-pip cmake ninja-build ccache libffi-dev libssl-dev dfu-util
        git clone -b v5.2 --recursive https://github.com/espressif/esp-idf.git
        ./esp-idf/install.sh esp32s3
        . ./esp-idf/export.sh
        cp -r esp-idf/examples/get-started/hello_world/* .
        idf.py set-target esp32s3
        idf.py build

    - name: Upload firmware artifact
      uses: actions/upload-artifact@v4
      with:
        name: hello_world_bin
        path: build/hello_world.bin
