name: ESP32-S3 PlatformIO Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ✅ Use latest checkout v4
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # ✅ Install PlatformIO
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      # ✅ Build firmware
      - name: Build firmware
        run: pio run

      # ✅ Upload artifact with NEW v4
      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: .pio/build/esp32-s3-devkitc-1/firmware.bin
